# main structure of the app
# define services and template environment variables
version: '2'
services:      
  redis:
    image: redis
  mongo:
    image: mongo
  web:
    build: ./src/web/
    environment:    
     - NODE_ENV
  broker:
    build: ./src/broker/   
    environment:    
     - NODE_ENV
  users:
    build: ./src/services/usersservice/
    environment:    
     - NODE_ENV
  logger:
    build: ./src/services/loggerservice/
    environment:     
     - NODE_ENV