version: '2'
services:      
  redis:
    image: redis
  mongo:
    image: mongo  
  web:
    extends:
      file: docker-compose.yml
      service: web
    command: npm test
  broker:
    build: ./src/broker/
    ports: 
     - "1883:1883"
    environment:
    - SERVICE_HOST=0.0.0.0
    - SERVICE_PORT=1883
    - NODE_ENV   
  users:
    build: ./src/services/usersservice/
    environment:
     - SERVICE_HOST=0.0.0.0
     - SERVICE_PORT=3001
     - NODE_ENV
  logger:
    build: ./src/services/loggerservice/
    environment:
     - SERVICE_HOST=0.0.0.0
     - SERVICE_PORT=3002
     - NODE_ENV